[package]
name = "flashblocks-payload"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true


[dependencies]

# reth
reth.workspace = true
reth-basic-payload-builder.workspace = true
reth-chain-state.workspace = true
reth-evm.workspace = true
reth-optimism-node.workspace = true
reth-optimism-chainspec.workspace = true
reth-optimism-payload-builder.workspace = true
reth-optimism-primitives.workspace = true
reth-provider.workspace = true
reth-primitives.workspace = true
reth-transaction-pool.workspace = true
reth-primitives-traits.workspace = true
reth-payload-util.workspace = true

# tokio
tokio.workspace = true
